export const countryList = [
  {label: 'Türkiye', value: 'Türkiye'},
  {label: 'USA', value: 'USA'},
  {label: 'Canada', value: 'Canada'},
  {label: 'Afghanistan', value: 'Afghanistan'},
  {label: 'Albania', value: 'Albania'},
  {label: 'Argentina', value: 'Argentina'},
  {label: 'Azerbaijan', value: 'United Kingdom'},
  {label: 'Iraq', value: 'Iraq'},
  {label: 'Germany', value: 'Germany'},
  {label: 'Turkmenistan', value: 'Turkmenistan'},
  {label: 'Syrian Arab Republic', value: 'Syrian Arab Republic'},
  {label: 'Iran', value: 'Iran'},
  {label: 'Russian Federation', value: 'Russian Federation'},
  {label: 'Uzbekistan', value: 'Uzbekistan'},
  {label: 'Egypt', value: 'Egypt'},
  {label: 'Other', value: 'Other'},
];
